---@class Mapper.keymap
---@field rhs? string
---@field callback? function
---@field desc? string
---@field condition? function
---@field priority? number
---@alias Mapper.maps table<string,Mapper.keymap>
---@class Mapper.Allmaps
---@field i Mapper.maps
---@field n Mapper.maps
---@field x Mapper.maps
---@field o Mapper.maps
---@field t Mapper.maps
